const Arrow=()=> <span aria-hidden="true">↗</span>;
const services=[["01","Advertising","Campaign systems built around clear offers, conversion paths and measurable acquisition."],["02","Lead Generation","Focused acquisition journeys that capture intent, qualify demand and support faster follow-up."],["03","Digital Marketing","Channel strategy, creative direction and optimization connected to business outcomes."],["04","Conversion Systems","Landing experiences, routing and CRM-ready flows that reduce friction between click and customer."]];
export default function Home(){return <main>
<header className="nav"><a className="brand" href="#top" aria-label="Click Nuvia home"><span className="mark">CN</span><span>CLICK <b>NUVIA</b></span></a><nav aria-label="Primary"><a href="#services">Services</a><a href="#system">How it works</a><a href="#platform">Remodeling platform</a><a href="#about">About</a></nav><a className="navCta" href="#services">Explore services <Arrow/></a><details className="mobileMenu"><summary aria-label="Open navigation">Menu</summary><div><a href="#services">Services</a><a href="#system">How it works</a><a href="#platform">Remodeling platform</a><a href="#about">About</a><a href="https://www.clicknuviaremodeling.com">Click Nuvia Remodeling</a></div></details></header>
<section id="top" className="hero"><div className="heroCopy"><p className="eyebrow">CUSTOMER ACQUISITION, ENGINEERED.</p><h1>Turn attention into <em>qualified demand.</em></h1><p className="lead">Click Nuvia brings advertising, lead generation, digital marketing and conversion systems into one focused growth journey.</p><div className="actions"><a className="primary" href="#services">Explore our services <Arrow/></a><a className="secondary" href="https://www.clicknuviaremodeling.com">See Click Nuvia Remodeling <Arrow/></a></div><div className="heroNotes"><span>Strategy before spend</span><span>Conversion-focused journeys</span><span>Clear handoff to sales</span></div></div><div className="growthPanel" aria-label="Click Nuvia acquisition system"><div className="panelTop"><span>CLICK NUVIA / GROWTH SYSTEM</span><i>LIVE FLOW</i></div><div className="flow"><article><small>01</small><strong>ATTENTION</strong><p>Advertising & audience</p></article><b>→</b><article><small>02</small><strong>INTENT</strong><p>Landing & qualification</p></article><b>→</b><article><small>03</small><strong>ACTION</strong><p>CRM & sales handoff</p></article></div><div className="signal"><span>Every step has one job:</span><strong>Move the right prospect forward.</strong></div></div></section>
<section className="proof"><span>Advertising</span><i/> <span>Lead Generation</span><i/> <span>Digital Marketing</span><i/> <span>Conversion</span></section>
<section id="services" className="section services"><div className="sectionHead"><p className="eyebrow">WHAT WE DO</p><h2>Four capabilities.<br/>One acquisition system.</h2><p>Each service can stand alone, but the strongest experience comes from connecting acquisition, qualification and sales handoff instead of optimizing isolated channels.</p></div><div className="serviceGrid">{services.map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></section>
<section id="system" className="system"><div><p className="eyebrow light">THE CLICK NUVIA METHOD</p><h2>From campaign to customer conversation.</h2><p>We design the journey around what should happen after the click—not just how to generate the click.</p></div><ol><li><b>01</b><div><strong>Attract</strong><p>Reach the right audience with a clear offer and channel strategy.</p></div></li><li><b>02</b><div><strong>Convert</strong><p>Use fast, focused landing experiences that make the next action obvious.</p></div></li><li><b>03</b><div><strong>Qualify</strong><p>Capture the signals sales teams actually need before follow-up.</p></div></li><li><b>04</b><div><strong>Operate</strong><p>Route opportunities into a workflow where they can be tracked and acted on.</p></div></li></ol></section>
<section id="platform" className="platform"><div className="platformCard"><p className="eyebrow">A CLICK NUVIA PRODUCT</p><h2>Click Nuvia Remodeling</h2><p>A dedicated U.S. home-remodeling lead-generation platform that turns homeowner project intent into structured, qualified opportunities.</p><div className="miniFlow"><span>Homeowner intent</span><b>→</b><span>Project qualification</span><b>→</b><span>Remodeling opportunity</span></div><a className="primary" href="https://www.clicknuviaremodeling.com">Visit the remodeling platform <Arrow/></a></div><aside><small>WHY IT EXISTS</small><strong>Vertical products let the acquisition system fit the market—not the other way around.</strong><p>Click Nuvia Remodeling applies the same conversion discipline to a specific industry with its own customer journey, qualification logic and operations.</p></aside></section>
<section id="about" className="section about"><div><p className="eyebrow">ABOUT CLICK NUVIA</p><h2>Built around outcomes, not channel noise.</h2></div><p>Click Nuvia is a customer-acquisition company focused on the connected system between marketing activity and real commercial opportunity. The work spans advertising, lead generation, digital marketing and the conversion layer that connects them.</p></section>
<section className="final"><p className="eyebrow light">ONE CLEAR NEXT STEP</p><h2>Start with the service that matches the growth problem.</h2><a className="primary inverse" href="#services">Review services <Arrow/></a></section>
<footer><a className="brand" href="#top"><span className="mark">CN</span><span>CLICK <b>NUVIA</b></span></a><p>Advertising · Lead Generation · Digital Marketing · Conversion Systems</p><div><a href="/privacy">Privacy</a><a href="/terms">Terms</a><a href="https://www.clicknuviaremodeling.com">Click Nuvia Remodeling</a></div><small>© 2026 Click Nuvia. All rights reserved.</small></footer>
</main>}
